media:
  input: /media
  output: media
content:
  - name: polaroids
    label: Polaroids
    type: collection
    path: 'polaroids'
    view: 
      fields: [ musician_name, band_name, image, image_hover ]
    fields:
      - name: musician_name
        label: Musician name
        type: string
      - name: band_name
        label: Band name
        type: string
      - name: image
        label: Image
        type: image
      - name: image_hover
        label: Image (on hover)
        type: image
  - name: site
    label: Site settings
    type: file
    path: src/_data/site.json
    fields:
      - name: title
        label: SEO title
        type: string
        options:
          maxlength: 60
      - name: description
        label: SEO description
        type: string
        maxlength: 160
      - name: email
        label: Email address
        type: string
      - name: instagram_handle
        label: Instagram 
        type: string