media:
  input: _site/media
  output: media
content:
  - name: polaroids
    label: Polaroids
    type: collection
    path: polaroids
    view: 
      fields: [ Musician_Name, Band_Name ]
      search: [ Musician_Name, Band_Name ]
      sort: [ Musician_Name, Band_Name ]
    fields:
      - name: Musician_Name
        label: Musician name
        type: string
      - name: Band_Name
        label: Band name
        type: string
      - name: Image_Src
        label: Image
        type: image
      - name: Hover_Image_Src
        label: Image (on hover)
        type: image
  # - name: site
  #   label: Site settings
  #   type: file
  #   path: '_data/site.json'
  #   fields:
  #     - name: title
  #       label: SEO title
  #       type: string
  #       options:
  #         maxlength: 60
  #     - name: description
  #       label: SEO description
  #       type: string
  #       options:
  #         maxlength: 160
  #     - name: email
  #       label: Email address
  #       type: string
  #     - name: instagram_handle
  #       label: Instagram 
  #       type: string