media:
  input: /media
  output: media
content:
  - name: polaroids
    label: Polaroid
    type: collection
    fields:
      - name: musician_name
        label: Musician name
        type: string
      - name: band_name
        label: Band name
        type: string