media:
  input: _site/media
  output: /media
content:
  - name: polaroids
    label: Polaroids
    type: collection
    path: src/polaroids
    format: yaml-frontmatter
    filename: '{year}-{month}-{day}-{primary}.md'
    view: 
      fields: [ Musician_Name, Band_Name ]
      search: [ Musician_Name, Band_Name ]
      sort: [ Musician_Name, Band_Name ]
      primary: Band_Name
    fields:
      - name: Musician_Name
        label: Musician name
        type: string
      - name: Band_Name
        label: Band name
        type: string
      - name: Image_Src
        label: Image
        type: image
      - name: Hover_Image_Src
        label: Image (on hover)
        type: image